import type { MetadataRoute } from "next";

// PWA manifest — makes Mimir installable (add-to-home-screen on mobile,
// app window on desktop). Icons are generated by scripts/generate-icons.mjs.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Mimir",
    short_name: "Mimir",
    description: "CRM de prospection pour le courtage en assurance.",
    lang: "fr",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#f7f8fa",
    theme_color: "#4f46e5",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
