import type { MetadataRoute } from "next";
import { DEFAULT_BRAND_NAME, DEFAULT_BRAND_TAGLINE } from "@/lib/brand";

// PWA manifest — makes the app installable (add-to-home-screen on mobile,
// app window on desktop). Icons are generated by scripts/generate-icons.mjs.
// Deployment brand, not tenant brand: this is served without a session.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: DEFAULT_BRAND_NAME,
    short_name: DEFAULT_BRAND_NAME,
    description: DEFAULT_BRAND_TAGLINE,
    lang: "fr",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#f7f8fa",
    theme_color: "#4f46e5",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
